#ddev-generated
# Simple template to demonstrate ddev-vnc
services:
  ddev-vnc:
    container_name: ddev-${DDEV_SITENAME}-ddev-vnc
    image: busybox:stable
    command: tail -f /dev/null
    networks: [default, ddev_default]
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"
